"""DatasetCulomns  table

Revision ID: 3c99967d8c57
Revises: 59efcef48c32
Create Date: 2026-06-28 09:58:26.844157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3c99967d8c57'
down_revision: Union[str, Sequence[str], None] = '59efcef48c32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataset_columns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('data_type', sa.String(length=100), nullable=False),
    sa.Column('is_nullable', sa.Boolean(), nullable=False),
    sa.Column('semantic_type', sa.String(length=100), nullable=True),
    sa.Column('valid_ratio', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dataset_columns')
    # ### end Alembic commands ###
