"""added row_count and null_ratio to datasetcolumns

Revision ID: 47b49ede07e8
Revises: 3953d6349b89
Create Date: 2026-06-29 10:05:15.554729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '47b49ede07e8'
down_revision: Union[str, Sequence[str], None] = '3953d6349b89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset_columns', sa.Column('row_count', sa.Integer(), nullable=False))
    op.add_column('dataset_columns', sa.Column('null_ratio', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dataset_columns', 'null_ratio')
    op.drop_column('dataset_columns', 'row_count')
    # ### end Alembic commands ###
