"""adding cascade to datasource_id in scanjobs

Revision ID: 843828260527
Revises: e2c06f59a81a
Create Date: 2026-07-06 11:07:09.187321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '843828260527'
down_revision: Union[str, Sequence[str], None] = 'e2c06f59a81a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('scan_jobs_datasource_id_fkey'), 'scan_jobs', type_='foreignkey')
    op.create_foreign_key(None, 'scan_jobs', 'data_sources', ['datasource_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scan_jobs', type_='foreignkey')
    op.create_foreign_key(op.f('scan_jobs_datasource_id_fkey'), 'scan_jobs', 'data_sources', ['datasource_id'], ['id'])
    # ### end Alembic commands ###
