"""create audit_logs table

Revision ID: e2c06f59a81a
Revises: 9f055b731661
Create Date: 2026-07-02 14:00:50.529407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e2c06f59a81a'
down_revision: Union[str, Sequence[str], None] = '9f055b731661'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('CREATE_DATASOURCE', 'UPDATE_DATASOURCE', 'DELETE_DATASOURCE', 'START_SCAN', 'SUBMIT_DATASET', 'APPROVE_DATASET', 'REJECT_DATASET', 'ASSIGN_TAG', 'REMOVE_TAG', name='auditaction'), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
